ACE_SettingsConfig {
 m_aInitialModSettings {
  ACE_Medical_Circulation_Settings "{65D2FB432916B718}" {
   m_CardiacArrestDamageEffect ACE_Medical_CardiacArrestDamageEffect "{622ECE676AA733F5}" {
    m_fBrainDamageRate 0.12
    m_fEffectStartDelayS 60
   }
   m_bCardiacArrestForAIEnabled 0
   m_fCPRSuccessCheckTimeoutS 15
   m_fCPRSuccessChanceMin 0.2
   m_fCPRSuccessChanceMax 0.75
   m_fAmmoniumCarbonateSuccessChanceMin 0.5
   m_fCardiacArrestMaxTotalBleedingRate 5
  }
  ACE_Medical_Breathing_Settings "{6612DD937E52BB6A}" {
   m_fAirwayObstructionChance 0.08
   m_fVomitChancePerMinute 0.02
   m_fVomitCooldown 15
   m_fPneumothoraxChance 0.25
   m_fPneumothoraxDeteriorationChancePerMinute 0.15
   m_fPneumothoraxArrestEnabled 0
   m_fTensionPneumothoraxChance 0.05
   m_fDeteriorateToTensionPneumothoraxChancePerMinute 0.01
   m_bPaCO2Enabled 0
   m_bKidneyEnabled 0
  }
  ACE_Overheating_Settings "{65FA13A496B871DE}" {
   m_fJamChanceScale 0
   m_fClearJamFailureChance 0.05
  }
  ACE_CookOff_Settings "{664F3A78A7FAB508}" {
   m_fMinCookOffDelay 8
   m_fMaxCookOffDelay 20
  }
 }
}
