SCR_MissionHeader {
 World "{0CA415DC09016613}Worlds/EveronSimpleRP/EveronSimpleRP.ent"
 m_sName "PAG — Everon"
 m_sAuthor "Jack Lania"
 m_sDescription "Penguin Assault Group : milsim semi-RP armée française sur Everon. Base de Levie, grades, certifications, ressources persistantes."
 m_sDetails "Serveur en développement. Respect de la chaîne de commandement, pas de tir ami, RP obligatoire. Commandes : /aide"
 m_sIcon "{7AC67A4B96915B22}Assets/Ecussons/PAG_BCR.edds"
 m_sLoadingScreen "{4AD77CF5F334891F}Assets/pag_wall.edds"
 m_sPreviewImage "{4AD77CF5F334891F}Assets/pag_wall.edds"
 m_sGameMode "Roleplay"
 m_iPlayerCount 40
 m_bOverrideScenarioTimeAndWeather 1
 m_iStartingHours 8
 m_iStartingMinutes 0
 m_fDayTimeAcceleration 1
 m_fNightTimeAcceleration 1
 m_bRandomStartingWeather 1
 m_bRandomWeatherChanges 1
 m_iMapMarkerLimitPerPlayer 30
 m_bIsArmavisionAllowedInMP 1
 m_ACE_Settings ACE_MissionHeaderSettings "{6A5CDC06764FA1B2}" {
  m_ACE_Finger_Settings ACE_Finger_Settings "{6A5CDC067125C237}" {
   m_fMaxPointingDistanceM 1000
   m_bCanPingAttach 1
   m_fPingRangeM 15
   m_fMapPointingRangeM 15
  }
  m_ACE_Medical_Core ACE_Medical_Core_Settings "{6A5CDC06733DF711}" {
   m_fDefaultResilienceRegenScale 0.3
   m_fResilienceDamageScale 1
   m_fMinHealthScaledForEpinephrine 0.33
   m_bPlayerCannotDie 0
   m_bLitterEnabled 1
   m_fLitterCleanUpTime 300
   m_bBleedOutForPlayersEnabled 1
   m_fBleedingRateScale 0.7
   m_fMaxTotalBleedingRate 5
   m_fBloodRegenScale 0.5
   m_ePainScreenEffectType WHITE_FLASH
   m_fSecondChanceResilienceRegenScale 0.5
   m_fDefaultSecondChance 1
   m_fSecondChanceOnHead 1
   m_fSecondChanceOnChest 1
   m_fSecondChanceOnAbdomen 1
   m_bSecondChanceForFallDamageEnabled 1
   m_bSecondChanceForAIEnabled 0
  }
  m_ACE_Medical_Hitzones ACE_Medical_Hitzones_Settings "{6A5CDC066D51995F}" {
   m_bOrganHitZonesEnabled 1
   m_fSecondChanceOnHeart 1
   m_bInstantUnconOnMassiveBleeding 0
  }
 }
 m_bWeatherConditionsAffectsAI 1
 m_bMovementAffectsAIAimAccuracy 1
 m_bLowLightEnvironmentAffectsAI 1
 m_bPerceivedFactionChangesAffectsAI 1
}