SRP_CertifTree {
 m_aRules {
  SRP_CertifRule "{6A5B0C0D0E0F5001}" {
   m_sTitle "CDG : FGI + OR, Caporal"
   m_eCertif CDG
   m_iPrerequisites 1025
   m_eMinGrade CAPORAL
  }
  SRP_CertifRule "{6A5B0C0D0E0F5002}" {
   m_sTitle "Médecin : FGI + Infirmier, Caporal"
   m_eCertif MEDECIN
   m_iPrerequisites 3
   m_eMinGrade CAPORAL
  }
  SRP_CertifRule "{6A5B0C0D0E0F5003}" {
   m_sTitle "PL : FGI + VL"
   m_eCertif COND_LOURD
   m_iPrerequisites 9
   m_eMinGrade RECRUE
  }
  SRP_CertifRule "{6A5B0C0D0E0F5004}" {
   m_sTitle "Blindé : FGI + VL + PL, Caporal"
   m_eCertif BLINDE
   m_iPrerequisites 25
   m_eMinGrade CAPORAL
  }
  SRP_CertifRule "{6A5B0C0D0E0F5005}" {
   m_sTitle "Pilote : FGI + VL, Caporal"
   m_eCertif PILOTE
   m_iPrerequisites 9
   m_eMinGrade CAPORAL
  }
  SRP_CertifRule "{6A5B0C0D0E0F5006}" {
   m_sTitle "TP : FGI, Caporal"
   m_eCertif TP
   m_iPrerequisites 1
   m_eMinGrade CAPORAL
  }
 }
 m_aGradeRules {
  SRP_GradeRule "{6A5B0C0D0E0F5101}" {
   m_sTitle "1re classe : 10 h, 8 missions"
   m_eGrade PREMIERE_CLASSE
   m_iMinSpecialties 0
   m_iMinHours 10
   m_iMinMissions 8
   m_iRequiredCertifs 1
  }
  SRP_GradeRule "{6A5B0C0D0E0F5102}" {
   m_sTitle "Caporal : 25 h, 20 missions"
   m_eGrade CAPORAL
   m_iMinSpecialties 0
   m_iMinHours 25
   m_iMinMissions 20
   m_iRequiredCertifs 1
  }
  SRP_GradeRule "{6A5B0C0D0E0F5103}" {
   m_sTitle "Caporal-chef : 50 h, 40 missions"
   m_eGrade CAPORAL_CHEF
   m_iMinSpecialties 0
   m_iMinHours 50
   m_iMinMissions 40
   m_iRequiredCertifs 1
  }
  SRP_GradeRule "{6A5B0C0D0E0F5104}" {
   m_sTitle "Sergent : CDG, 100 h, 70 missions"
   m_eGrade SERGENT
   m_iMinSpecialties 0
   m_iMinHours 100
   m_iMinMissions 70
   m_iRequiredCertifs 8193
  }
  SRP_GradeRule "{6A5B0C0D0E0F5105}" {
   m_sTitle "Sergent-chef : CDG, 200 h, 120 missions"
   m_eGrade SERGENT_CHEF
   m_iMinSpecialties 0
   m_iMinHours 200
   m_iMinMissions 120
   m_iRequiredCertifs 8193
  }
  SRP_GradeRule "{6A5B0C0D0E0F5106}" {
   m_sTitle "Adjudant : CDG, 400 h, 200 missions"
   m_eGrade ADJUDANT
   m_iMinSpecialties 0
   m_iMinHours 400
   m_iMinMissions 200
   m_iRequiredCertifs 8193
  }
 }
}
