ActionManager {
 Actions {
  Action SRP_VoiceRange {
   InputSource InputSourceSum "{6A5B0C0D0E0F4001}" {
    Sources {
     InputSourceValue "{6A5B0C0D0E0F4003}" {
      FilterPreset "click"
      Input "keyboard:KC_F9"
     }
     InputSourceCombo "{6A5B0C0D0E0F4031}" {
      FilterPreset "gamepad:click"
      Sources {
       InputSourceValue "{6A5B0C0D0E0F4032}" {
        Input "gamepad0:shoulder_left"
       }
       InputSourceValue "{6A5B0C0D0E0F4033}" {
        Input "gamepad0:pad_up"
        Filter InputFilterDown "{6A5B0C0D0E0F4034}" {
        }
       }
      }
     }
    }
   }
  }
  Action SRP_StaffMenu {
   InputSource InputSourceSum "{6A5B0C0D0E0F4011}" {
    Sources {
     InputSourceValue "{6A5B0C0D0E0F4013}" {
      FilterPreset "click"
      Input "keyboard:KC_F10"
     }
     InputSourceCombo "{6A5B0C0D0E0F4051}" {
      FilterPreset "gamepad:click"
      Sources {
       InputSourceValue "{6A5B0C0D0E0F4052}" {
        Input "gamepad0:view"
       }
       InputSourceValue "{6A5B0C0D0E0F4053}" {
        Input "gamepad0:x"
        Filter InputFilterHoldOnce "{6A5B0C0D0E0F4054}" {
         HoldDuration 500
        }
       }
      }
     }
    }
   }
  }
  Action SRP_Earplugs {
   InputSource InputSourceSum "{6A5B0C0D0E0F4021}" {
    Sources {
     InputSourceValue "{6A5B0C0D0E0F4023}" {
      FilterPreset "click"
      Input "keyboard:KC_F8"
     }
     InputSourceCombo "{6A5B0C0D0E0F4041}" {
      FilterPreset "gamepad:click"
      Sources {
       InputSourceValue "{6A5B0C0D0E0F4042}" {
        Input "gamepad0:shoulder_left"
       }
       InputSourceValue "{6A5B0C0D0E0F4043}" {
        Input "gamepad0:pad_down"
        Filter InputFilterDown "{6A5B0C0D0E0F4044}" {
        }
       }
      }
     }
    }
   }
  }
 }
 Contexts {
  ActionContext IngameContext {
   ActionRefs +{
    "SRP_VoiceRange"
    "SRP_StaffMenu"
    "SRP_Earplugs"
   }
  }
 }
}
