MenuManager {
 MenuPresets {
  MenuPreset SRP_TerminalMenu {
   Layout "{6A5B7C8D9E0F1A2D}UI/Layouts/SimpleRP/SRP_PC.layout"
   Class "SRP_TerminalMenu"
  }
  MenuPreset SRP_AdminMenu {
   Layout "{6A5B7C8D9E0F1A2D}UI/Layouts/SimpleRP/SRP_PC.layout"
   Class "SRP_AdminMenu"
  }
  MenuPreset SRP_SoldierMenu {
   Layout "{6A5B7C8D9E0F1A2D}UI/Layouts/SimpleRP/SRP_PC.layout"
   Class "SRP_SoldierMenu"
  }
  MenuPreset SRP_RequestMenu {
   Layout "{6A5B7C8D9E0F1A2D}UI/Layouts/SimpleRP/SRP_PC.layout"
   Class "SRP_RequestMenu"
  }
  MenuPreset SRP_ControlMenu {
   Layout "{6A5B7C8D9E0F1A2D}UI/Layouts/SimpleRP/SRP_PC.layout"
   Class "SRP_ControlMenu"
  }
  MenuPreset SRP_PCMenu {
   Layout "{6A5B7C8D9E0F1A2D}UI/Layouts/SimpleRP/SRP_PC.layout"
   Class "SRP_PCMenu"
  }
  MenuPreset SRP_CharteMenu {
   Layout "{6A5B7C8D9E0F1A2D}UI/Layouts/SimpleRP/SRP_PC.layout"
   Class "SRP_CharteMenu"
  }
 }
}
