SCR_KeyBindingMenuConfig {
 m_KeyBindingCategories {
  SCR_KeyBindingCategory "{6A5B0C0D0E0F4020}" {
   m_sName "PAG"
   m_sDisplayName "PAG"
   m_KeyBindingEntries {
    SCR_KeyBindingEntry "{6A5B0C0D0E0F4025}" {
     m_sActionName "SRP_Earplugs"
     m_sDisplayName "Bouchons"
     m_sPreset "click"
    }
    SCR_KeyBindingEntry "{6A5B0C0D0E0F4005}" {
     m_sActionName "SRP_VoiceRange"
     m_sDisplayName "Portée de voix"
     m_sPreset "click"
    }
    SCR_KeyBindingEntry "{6A5B0C0D0E0F4015}" {
     m_sActionName "SRP_StaffMenu"
     m_sDisplayName "Menu Staff"
     m_sPreset "click"
    }
   }
  }
 }
}
